// Provider profiles maintained by llmux.
package compat

var profiles = map[string]Profile{
	"abacus":                              {ID: "abacus", DisplayName: "Abacus", BaseURL: "https://routellm.abacus.ai/v1", EnvKey: "ABACUS_API_KEY", Behavior: BehaviorFull},
	"abliteration_ai":                     {ID: "abliteration_ai", DisplayName: "Abliteration AI", BaseURL: "https://api.abliteration.ai/v1", EnvKey: "ABLIT_KEY", Behavior: BehaviorFull},
	"ai21":                                {ID: "ai21", DisplayName: "AI21 Labs", BaseURL: "https://api.ai21.ai/v1", EnvKey: "AI21_API_KEY", Behavior: BehaviorFull},
	"ai302":                               {ID: "ai302", DisplayName: "302.AI", BaseURL: "https://api.302.ai/v1", EnvKey: "AI302_API_KEY", Behavior: BehaviorFull},
	"ai_router":                           {ID: "ai_router", DisplayName: "AI-ROUTER", BaseURL: "https://api.ai-router.dev/v1", EnvKey: "AI_ROUTER_API_KEY", Behavior: BehaviorFull},
	"aiand":                               {ID: "aiand", DisplayName: "AIand", BaseURL: "https://api.aiand.com/v1", EnvKey: "AIAND_API_KEY", Behavior: BehaviorFull},
	"aibadgr":                             {ID: "aibadgr", DisplayName: "AI Badgr", BaseURL: "https://api.aibadgr.com/v1", EnvKey: "AIBADGR_API_KEY", Behavior: BehaviorFull},
	"aigc2d":                              {ID: "aigc2d", DisplayName: "AIGC2D", BaseURL: "https://api.aigc2d.com/v1", EnvKey: "AIGC2D_API_KEY", Behavior: BehaviorFull},
	"aihubmix":                            {ID: "aihubmix", DisplayName: "AIHubMix", BaseURL: "https://aihubmix.com/v1", EnvKey: "AIHUBMIX_API_KEY", Behavior: BehaviorFull},
	"ails":                                {ID: "ails", DisplayName: "AILS", BaseURL: "https://api.caipacity.com/v1", EnvKey: "AILS_API_KEY", Behavior: BehaviorFull},
	"aiml":                                {ID: "aiml", DisplayName: "AI/ML API", BaseURL: "https://api.aimlapi.com/v1", EnvKey: "AIML_API_KEY", Behavior: BehaviorFull},
	"aki_io":                              {ID: "aki_io", DisplayName: "AKI.IO", BaseURL: "https://aki.io/openai/v1", EnvKey: "AKI_IO_API_KEY", Behavior: BehaviorFull},
	"albert":                              {ID: "albert", DisplayName: "Albert", BaseURL: "https://api.albert.ai/v1", EnvKey: "ALBERT_API_KEY", Behavior: BehaviorFull},
	"alibaba":                             {ID: "alibaba", DisplayName: "Alibaba Cloud (DashScope)", BaseURL: "https://dashscope-intl.aliyuncs.com/apps/anthropic", EnvKey: "ALIBABA_API_KEY", Behavior: BehaviorFull, Protocol: ProtocolAnthropic},
	"alibaba_coding_plan":                 {ID: "alibaba_coding_plan", DisplayName: "Alibaba Coding Plan", BaseURL: "https://coding-intl.dashscope.aliyuncs.com/apps/anthropic", EnvKey: "ALIBABA_CODING_PLAN_API_KEY", Behavior: BehaviorFull, Protocol: ProtocolAnthropic},
	"alibaba_coding_plan_cn":              {ID: "alibaba_coding_plan_cn", DisplayName: "Alibaba Coding Plan (China)", BaseURL: "https://coding.dashscope.aliyuncs.com/apps/anthropic", EnvKey: "ALIBABA_CODING_PLAN_API_KEY", Behavior: BehaviorFull, Protocol: ProtocolAnthropic},
	"alibaba_token_plan":                  {ID: "alibaba_token_plan", DisplayName: "Alibaba Token Plan", BaseURL: "https://token-plan.ap-southeast-1.maas.aliyuncs.com/apps/anthropic", EnvKey: "ALIBABA_TOKEN_PLAN_API_KEY", Behavior: BehaviorFull, Protocol: ProtocolAnthropic},
	"alibaba_token_plan_cn":               {ID: "alibaba_token_plan_cn", DisplayName: "Alibaba Token Plan (China)", BaseURL: "https://token-plan.cn-beijing.maas.aliyuncs.com/apps/anthropic", EnvKey: "ALIBABA_TOKEN_PLAN_API_KEY", Behavior: BehaviorFull, Protocol: ProtocolAnthropic},
	"ambient":                             {ID: "ambient", DisplayName: "Ambient", BaseURL: "https://api.ambient.xyz/v1", EnvKey: "AMBIENT_API_KEY", Behavior: BehaviorFull},
	"anyapi":                              {ID: "anyapi", DisplayName: "AnyAPI", BaseURL: "https://api.anyapi.ai/v1", EnvKey: "ANYAPI_KEY", Behavior: BehaviorFull},
	"anyscale":                            {ID: "anyscale", DisplayName: "Anyscale", BaseURL: "https://api.endpoints.anyscale.com/v1", EnvKey: "ANYSCALE_API_KEY", Behavior: BehaviorFull},
	"apertis":                             {ID: "apertis", DisplayName: "Apertis", BaseURL: "https://api.stima.tech/v1", EnvKey: "STIMA_API_KEY", Behavior: BehaviorFull},
	"api2d":                               {ID: "api2d", DisplayName: "API2D", BaseURL: "https://oa.api2d.net/v1", EnvKey: "API2D_API_KEY", Behavior: BehaviorFull},
	"api2gpt":                             {ID: "api2gpt", DisplayName: "API2GPT", BaseURL: "https://api.api2gpt.com/v1", EnvKey: "API2GPT_API_KEY", Behavior: BehaviorFull},
	"apiserpent":                          {ID: "apiserpent", DisplayName: "API Serpent", BaseURL: "https://api.apiserpent.com/v1", EnvKey: "APISERPENT_API_KEY", Behavior: BehaviorFull},
	"atlascloud":                          {ID: "atlascloud", DisplayName: "AtlasCloud", BaseURL: "https://api.atlascloud.com/v1", EnvKey: "ATLASCLOUD_API_KEY", Behavior: BehaviorFull},
	"atomic_chat":                         {ID: "atomic_chat", DisplayName: "Atomic Chat", BaseURL: "http://127.0.0.1:1337/v1", EnvKey: "ATOMIC_CHAT_API_KEY", Behavior: BehaviorFull},
	"auriko":                              {ID: "auriko", DisplayName: "Auriko", BaseURL: "https://api.auriko.ai/v1", EnvKey: "AURIKO_API_KEY", Behavior: BehaviorFull},
	"azure_ai":                            {ID: "azure_ai", DisplayName: "Azure AI", BaseURL: "https://models.inference.ai.azure.com", EnvKey: "AZURE_AI_API_KEY", Behavior: BehaviorFull},
	"baichuan":                            {ID: "baichuan", DisplayName: "Baichuan AI", BaseURL: "https://api.baichuan-ai.com/v1", EnvKey: "BAICHUAN_API_KEY", Behavior: BehaviorFull},
	"baidu":                               {ID: "baidu", DisplayName: "Baidu (文心/ERNIE)", BaseURL: "https://qianfan.baidubce.com/anthropic", EnvKey: "BAIDU_API_KEY", Behavior: BehaviorFull, Protocol: ProtocolAnthropic},
	"baidu_v2":                            {ID: "baidu_v2", DisplayName: "BaiduV2", BaseURL: "https://qianfan.baidubce.com/anthropic", EnvKey: "QIANFAN_API_KEY", Behavior: BehaviorFull, Protocol: ProtocolAnthropic},
	"bailing":                             {ID: "bailing", DisplayName: "Bailing", BaseURL: "https://api.ant-ling.com/v1", EnvKey: "BAILING_API_TOKEN", Behavior: BehaviorFull},
	"baseten":                             {ID: "baseten", DisplayName: "Baseten", BaseURL: "https://inference.baseten.co/v1", EnvKey: "BASETEN_API_KEY", Behavior: BehaviorFull},
	"berget":                              {ID: "berget", DisplayName: "Berget.AI", BaseURL: "https://api.berget.ai/v1", EnvKey: "BERGET_API_KEY", Behavior: BehaviorFull},
	"bigmodel":                            {ID: "bigmodel", DisplayName: "BigModel (智谱)", BaseURL: "https://open.bigmodel.cn/api/paas/v4", EnvKey: "BIGMODEL_API_KEY", Behavior: BehaviorFull},
	"blueclaw":                            {ID: "blueclaw", DisplayName: "Blue Claw", BaseURL: "https://openai.blueclaw.network/v1", EnvKey: "BLUECLAW_API_KEY", Behavior: BehaviorFull},
	"bytedance":                           {ID: "bytedance", DisplayName: "ByteDance", BaseURL: "https://ark.cn-beijing.volces.com/api/v3", EnvKey: "ARK_API_KEY", Behavior: BehaviorFull},
	"byteplus":                            {ID: "byteplus", DisplayName: "BytePlus (Volcano)", BaseURL: "https://ark.bytepluses.com/api/v3", EnvKey: "BYTEPLUS_API_KEY", Behavior: BehaviorFull},
	"bytez":                               {ID: "bytez", DisplayName: "Bytez", BaseURL: "https://api.bytez.com/v2", EnvKey: "BYTEZ_API_KEY", Behavior: BehaviorFull},
	"canopywave":                          {ID: "canopywave", DisplayName: "Canopywave", BaseURL: "https://api.canopywave.com/v1", EnvKey: "CANOPYWAVE_API_KEY", Behavior: BehaviorFull},
	"cerebras":                            {ID: "cerebras", DisplayName: "Cerebras", BaseURL: "https://api.cerebras.ai/v1", EnvKey: "CEREBRAS_API_KEY", Behavior: BehaviorFull},
	"chatgpt":                             {ID: "chatgpt", DisplayName: "ChatGPT (订阅)", BaseURL: "https://chatgpt.com/backend-api/codex", EnvKey: "CHATGPT_API_KEY", Behavior: BehaviorFull},
	"cherryin":                            {ID: "cherryin", DisplayName: "cherryin", BaseURL: "https://open.cherryin.net", EnvKey: "CHERRYIN_API_KEY", Behavior: BehaviorFull},
	"chutes":                              {ID: "chutes", DisplayName: "Chutes", BaseURL: "https://llm.chutes.ai/v1", EnvKey: "CHUTES_API_KEY", Behavior: BehaviorFull},
	"clarifai":                            {ID: "clarifai", DisplayName: "Clarifai", BaseURL: "https://api.clarifai.com/v2/ext/openai/v1", EnvKey: "CLARIFAI_API_KEY", Behavior: BehaviorFull},
	"claudinio":                           {ID: "claudinio", DisplayName: "Claudinio", BaseURL: "https://api.claudin.io", EnvKey: "CLAUDINIO_API_KEY", Behavior: BehaviorFull},
	"cline_pass":                          {ID: "cline_pass", DisplayName: "Cline", BaseURL: "https://api.cline.bot/v1", EnvKey: "CLINE_API_KEY", Behavior: BehaviorFull},
	"closeai":                             {ID: "closeai", DisplayName: "CloseAI", BaseURL: "https://api.closeai-proxy.xyz/v1", EnvKey: "CLOSEAI_API_KEY", Behavior: BehaviorFull},
	"cloudferro_sherlock":                 {ID: "cloudferro_sherlock", DisplayName: "CloudFerro Sherlock", BaseURL: "https://api-sherlock.cloudferro.com/openai/v1", EnvKey: "CLOUDFERRO_SHERLOCK_API_KEY", Behavior: BehaviorFull},
	"cloudflare":                          {ID: "cloudflare", DisplayName: "Cloudflare", BaseURL: "https://api.cloudflare.com/client/v4/accounts/{CLOUDFLARE_ACCOUNT_ID}/ai/v1", EnvKey: "CLOUDFLARE_API_KEY", Behavior: BehaviorFull, Protocol: ProtocolResponses},
	"cloudflare_workers_ai":               {ID: "cloudflare_workers_ai", DisplayName: "Cloudflare Workers AI", BaseURL: "https://api.cloudflare.com/client/v4/accounts/{CLOUDFLARE_ACCOUNT_ID}/ai/v1", EnvKey: "CLOUDFLARE_API_KEY", Behavior: BehaviorFull, Protocol: ProtocolResponses},
	"codestral":                           {ID: "codestral", DisplayName: "Codestral (Mistral)", BaseURL: "https://api.mistral.ai/v1", EnvKey: "CODESTRAL_API_KEY", Behavior: BehaviorFull},
	"cometapi":                            {ID: "cometapi", DisplayName: "CometAPI", BaseURL: "https://api.cometapi.com/v1", EnvKey: "COMETAPI_API_KEY", Behavior: BehaviorFull},
	"commandcode":                         {ID: "commandcode", DisplayName: "CommandCode", BaseURL: "https://api.commandcode.com/v1", EnvKey: "COMMANDCODE_API_KEY", Behavior: BehaviorFull},
	"compactifai":                         {ID: "compactifai", DisplayName: "CompactifAI", BaseURL: "https://api.compactif.ai/v1", EnvKey: "COMPACTIFAI_API_KEY", Behavior: BehaviorFull},
	"copilot":                             {ID: "copilot", DisplayName: "GitHub Copilot", BaseURL: "https://api.githubcopilot.com", EnvKey: "COPILOT_API_KEY", Behavior: BehaviorFull},
	"cortecs":                             {ID: "cortecs", DisplayName: "Cortecs", BaseURL: "https://api.cortecs.ai/v1/", EnvKey: "CORTECS_API_KEY", Behavior: BehaviorFull},
	"coze":                                {ID: "coze", DisplayName: "Coze (扣子)", BaseURL: "https://api.coze.cn/v1", EnvKey: "COZE_API_KEY", Behavior: BehaviorFull},
	"crof":                                {ID: "crof", DisplayName: "CrofAI", BaseURL: "https://crof.ai/v1", EnvKey: "CROF_API_KEY", Behavior: BehaviorFull},
	"crossmodel":                          {ID: "crossmodel", DisplayName: "CrossModel", BaseURL: "https://api.crossmodel.ai/v1", EnvKey: "CROSSMODEL_API_KEY", Behavior: BehaviorFull},
	"crusoe":                              {ID: "crusoe", DisplayName: "Crusoe", BaseURL: "https://api.inference.crusoecloud.com/v1", EnvKey: "CRUSOE_API_KEY", Behavior: BehaviorFull},
	"daoxe":                               {ID: "daoxe", DisplayName: "DaoXE", BaseURL: "https://daoxe.com/v1", EnvKey: "DAOXE_API_KEY", Behavior: BehaviorFull},
	"darkbloom":                           {ID: "darkbloom", DisplayName: "Darkbloom", BaseURL: "https://api.darkbloom.dev/v1", EnvKey: "DARKBLOOM_API_KEY", Behavior: BehaviorFull},
	"databricks":                          {ID: "databricks", DisplayName: "Databricks", BaseURL: "https://databricks.com/serving-endpoints", EnvKey: "DATABRICKS_API_KEY", Behavior: BehaviorFull},
	"datarobot":                           {ID: "datarobot", DisplayName: "DataRobot", BaseURL: "https://app.datarobot.com/api/v2", EnvKey: "DATAROBOT_API_TOKEN", Behavior: BehaviorFull},
	"deepbricks":                          {ID: "deepbricks", DisplayName: "DeepBricks", BaseURL: "https://api.deepbricks.ai/v1", EnvKey: "DEEPBRICKS_API_KEY", Behavior: BehaviorFull},
	"deepinfra":                           {ID: "deepinfra", DisplayName: "DeepInfra", BaseURL: "https://api.deepinfra.com/v1/openai", EnvKey: "DEEPINFRA_API_KEY", Behavior: BehaviorFull},
	"deepseek":                            {ID: "deepseek", DisplayName: "DeepSeek", BaseURL: "https://api.deepseek.com/v1", EnvKey: "DEEPSEEK_API_KEY", Behavior: BehaviorDeepSeek},
	"digitalocean":                        {ID: "digitalocean", DisplayName: "DigitalOcean", BaseURL: "https://inference.do-ai.run", EnvKey: "DIGITALOCEAN_ACCESS_TOKEN", Behavior: BehaviorFull},
	"dinference":                          {ID: "dinference", DisplayName: "DInference", BaseURL: "https://api.dinference.com/v1", EnvKey: "DINFERENCE_API_KEY", Behavior: BehaviorFull},
	"doubao":                              {ID: "doubao", DisplayName: "Doubao", BaseURL: "https://ark.cn-beijing.volces.com/api/v3", EnvKey: "ARK_API_KEY", Behavior: BehaviorFull},
	"doubleword":                          {ID: "doubleword", DisplayName: "Doubleword", BaseURL: "https://api.doubleword.ai/v1", EnvKey: "DOUBLEWORD_API_KEY", Behavior: BehaviorFull},
	"drun":                                {ID: "drun", DisplayName: "D.Run (China)", BaseURL: "https://chat.d.run/v1", EnvKey: "DRUN_API_KEY", Behavior: BehaviorFull},
	"ebcloud":                             {ID: "ebcloud", DisplayName: "EBCloud", BaseURL: "https://maas-api.ebcloud.com/v1", EnvKey: "EBCLOUD_API_KEY", Behavior: BehaviorFull},
	"embercloud":                          {ID: "embercloud", DisplayName: "Embercloud", BaseURL: "https://api.embercloud.com/v1", EnvKey: "EMBERCLOUD_API_KEY", Behavior: BehaviorFull},
	"empiriolabs":                         {ID: "empiriolabs", DisplayName: "EmpirioLabs AI", BaseURL: "https://api.empiriolabs.ai/v1", EnvKey: "EMPIRIOLABS_API_KEY", Behavior: BehaviorFull},
	"evroc":                               {ID: "evroc", DisplayName: "evroc", BaseURL: "https://models.think.evroc.com/v1", EnvKey: "EVROC_API_KEY", Behavior: BehaviorFull},
	"fastcrw":                             {ID: "fastcrw", DisplayName: "FastCRW", BaseURL: "https://fastcrw.com/api/v1", EnvKey: "FASTCRW_API_KEY", Behavior: BehaviorFull},
	"fastgpt":                             {ID: "fastgpt", DisplayName: "FastGPT", BaseURL: "https://api.fastgpt.in/v1", EnvKey: "FASTGPT_API_KEY", Behavior: BehaviorFull},
	"fastrouter":                          {ID: "fastrouter", DisplayName: "FastRouter", BaseURL: "https://api.fastrouter.ai/v1", EnvKey: "FASTROUTER_API_KEY", Behavior: BehaviorFull},
	"featherless_ai":                      {ID: "featherless_ai", DisplayName: "Featherless AI", BaseURL: "https://api.featherless.ai/v1", EnvKey: "FEATHERLESS_API_KEY", Behavior: BehaviorFull},
	"firepass":                            {ID: "firepass", DisplayName: "Fireworks (Firepass)", BaseURL: "https://api.fireworks.ai/inference/v1", EnvKey: "FIREWORKS_API_KEY", Behavior: BehaviorFull, Protocol: ProtocolResponses},
	"fireworks":                           {ID: "fireworks", DisplayName: "Fireworks", BaseURL: "https://api.fireworks.ai/inference/v1", EnvKey: "FIREWORKS_API_KEY", Behavior: BehaviorFull, Protocol: ProtocolResponses},
	"freemodel":                           {ID: "freemodel", DisplayName: "FreeModel", EnvKey: "FREEMODEL_API_KEY", Behavior: BehaviorFull},
	"friendliai":                          {ID: "friendliai", DisplayName: "FriendliAI", BaseURL: "https://inference.friendli.ai/v1", EnvKey: "FRIENDLIAI_API_KEY", Behavior: BehaviorFull},
	"frogbot":                             {ID: "frogbot", DisplayName: "FrogBot", BaseURL: "https://app.frogbot.ai/api/v1", EnvKey: "FROGBOT_API_KEY", Behavior: BehaviorFull},
	"galadriel":                           {ID: "galadriel", DisplayName: "Galadriel", BaseURL: "https://api.galadriel.com/v1", EnvKey: "GALADRIEL_API_KEY", Behavior: BehaviorFull},
	"gdc":                                 {ID: "gdc", DisplayName: "GDC", BaseURL: "https://api.gdc.ai/v1", EnvKey: "GDC_API_KEY", Behavior: BehaviorFull},
	"gigachat":                            {ID: "gigachat", DisplayName: "GigaChat (Sberbank)", BaseURL: "https://gigachat.devices.sberbank.ru/api/v1", EnvKey: "GIGACHAT_API_KEY", Behavior: BehaviorFull},
	"github":                              {ID: "github", DisplayName: "GitHub Models", BaseURL: "https://models.inference.ai.azure.com", EnvKey: "GITHUB_TOKEN", Behavior: BehaviorFull},
	"gmi":                                 {ID: "gmi", DisplayName: "GMI", BaseURL: "https://api.gmi-serving.com/v1", EnvKey: "GMI_API_KEY", Behavior: BehaviorFull},
	"gmicloud":                            {ID: "gmicloud", DisplayName: "GMI Cloud", BaseURL: "https://api.gmi-serving.com/v1", EnvKey: "GMI_API_KEY", Behavior: BehaviorFull},
	"gonka24":                             {ID: "gonka24", DisplayName: "Gonka24", BaseURL: "https://api.gonka24.com/v1", EnvKey: "GONKA24_API_KEY", Behavior: BehaviorFull},
	"gradient_ai":                         {ID: "gradient_ai", DisplayName: "Gradient AI", BaseURL: "https://inference.do-ai.run/v1", EnvKey: "GRADIENT_API_KEY", Behavior: BehaviorFull},
	"groq":                                {ID: "groq", DisplayName: "Groq", BaseURL: "https://api.groq.com/openai/v1", EnvKey: "GROQ_API_KEY", Behavior: BehaviorGroq, Protocol: ProtocolResponses},
	"helicone":                            {ID: "helicone", DisplayName: "Helicone", BaseURL: "https://api.helicone.ai/v1", EnvKey: "HELICONE_API_KEY", Behavior: BehaviorFull},
	"heroku":                              {ID: "heroku", DisplayName: "Heroku AI", BaseURL: "https://api.heroku.com/inference/v1", EnvKey: "HEROKU_API_KEY", Behavior: BehaviorFull},
	"hetzner":                             {ID: "hetzner", DisplayName: "Hetzner", BaseURL: "https://inference.hetzner.com/api/v1", EnvKey: "HETZNER_VLLM_API_KEY", Behavior: BehaviorFull},
	"hosted_vllm":                         {ID: "hosted_vllm", DisplayName: "Hosted vLLM", BaseURL: "https://hosted-vllm-api.com/v1", EnvKey: "HOSTED_VLLM_API_KEY", Behavior: BehaviorFull},
	"hpc_ai":                              {ID: "hpc_ai", DisplayName: "HPC-AI", BaseURL: "https://api.hpc-ai.com/inference/v1", EnvKey: "INFERENCE_API_KEY", Behavior: BehaviorFull},
	"hyperbolic":                          {ID: "hyperbolic", DisplayName: "Hyperbolic", BaseURL: "https://api.hyperbolic.xyz/v1", EnvKey: "HYPERBOLIC_API_KEY", Behavior: BehaviorFull},
	"iflowcn":                             {ID: "iflowcn", DisplayName: "iFlow", BaseURL: "https://apis.iflow.cn/v1", EnvKey: "IFLOW_API_KEY", Behavior: BehaviorFull},
	"inception":                           {ID: "inception", DisplayName: "Inception Labs", BaseURL: "https://api.inceptionlabs.ai/v1", EnvKey: "INCEPTION_API_KEY", Behavior: BehaviorFull},
	"inceptron":                           {ID: "inceptron", DisplayName: "Inceptron", BaseURL: "https://api.inceptron.io/v1", EnvKey: "INCEPTRON_API_KEY", Behavior: BehaviorFull},
	"inference_net":                       {ID: "inference_net", DisplayName: "Inference.net", BaseURL: "https://api.inference.net/v1", EnvKey: "INFERENCE_NET_API_KEY", Behavior: BehaviorFull},
	"inferencehub":                        {ID: "inferencehub", DisplayName: "InferenceHub", BaseURL: "https://app.inferencehub.tech/v1", EnvKey: "INFERENCEHUB_API_KEY", Behavior: BehaviorFull},
	"inferx":                              {ID: "inferx", DisplayName: "InferX", BaseURL: "https://model.inferx.net/v1", EnvKey: "INFERX_API_KEY", Behavior: BehaviorFull},
	"infinity":                            {ID: "infinity", DisplayName: "Infinity AI", BaseURL: "https://infinity.ai/api/v1", EnvKey: "INFINITY_API_KEY", Behavior: BehaviorFull},
	"io_net":                              {ID: "io_net", DisplayName: "IO.NET", BaseURL: "https://api.intelligence.io.solutions/api/v1", EnvKey: "IOINTELLIGENCE_API_KEY", Behavior: BehaviorFull},
	"jiekou":                              {ID: "jiekou", DisplayName: "Jiekou.AI", BaseURL: "https://api.highwayapi.ai/openai", EnvKey: "JIEKOU_API_KEY", Behavior: BehaviorFull},
	"kenari":                              {ID: "kenari", DisplayName: "Kenari", BaseURL: "https://kenari.id/v1", EnvKey: "KENARI_API_KEY", Behavior: BehaviorFull},
	"kilo":                                {ID: "kilo", DisplayName: "Kilo", BaseURL: "https://api.kilo.ai/v1", EnvKey: "KILO_API_KEY", Behavior: BehaviorFull},
	"kimi":                                {ID: "kimi", DisplayName: "Kimi", BaseURL: "https://api.moonshot.ai/v1", EnvKey: "MOONSHOT_API_KEY", Behavior: BehaviorFull},
	"kimi_for_coding":                     {ID: "kimi_for_coding", DisplayName: "Kimi For Coding", BaseURL: "https://api.kimi.com/coding/v1", EnvKey: "KIMI_API_KEY", Behavior: BehaviorFull},
	"kiro":                                {ID: "kiro", DisplayName: "Kiro", BaseURL: "https://api.kiro.dev/v1", EnvKey: "KIRO_API_KEY", Behavior: BehaviorFull},
	"kluster_ai":                          {ID: "kluster_ai", DisplayName: "Kluster AI", BaseURL: "https://api.kluster.ai/v1", EnvKey: "KLUSTER_API_KEY", Behavior: BehaviorFull},
	"krutrim":                             {ID: "krutrim", DisplayName: "Krutrim", BaseURL: "https://api.krutrim.ai/v1", EnvKey: "KRUTRIM_API_KEY", Behavior: BehaviorFull},
	"kuae_cloud_coding_plan":              {ID: "kuae_cloud_coding_plan", DisplayName: "KUAE Cloud Coding Plan", BaseURL: "https://coding-plan-endpoint.kuaecloud.net/v1", EnvKey: "KUAE_API_KEY", Behavior: BehaviorFull},
	"lambda_ai":                           {ID: "lambda_ai", DisplayName: "Lambda AI", BaseURL: "https://api.lambda.ai/v1", EnvKey: "LAMBDA_API_KEY", Behavior: BehaviorFull},
	"lemonade":                            {ID: "lemonade", DisplayName: "Lemonade", BaseURL: "http://localhost:13305/v1", EnvKey: "LEMONADE_API_KEY", Behavior: BehaviorFull},
	"lemonfox_ai":                         {ID: "lemonfox_ai", DisplayName: "Lemonfox AI", BaseURL: "https://api.lemonfox.ai/v1", EnvKey: "LEMONFOX_API_KEY", Behavior: BehaviorFull},
	"libertai":                            {ID: "libertai", DisplayName: "Libertai", BaseURL: "https://api.libertai.io/v1", EnvKey: "LIBERTAI_API_KEY", Behavior: BehaviorFull},
	"lilac":                               {ID: "lilac", DisplayName: "Lilac", BaseURL: "https://api.getlilac.com/v1", EnvKey: "LILAC_API_KEY", Behavior: BehaviorFull},
	"lingyiwanwu":                         {ID: "lingyiwanwu", DisplayName: "Lingyiwanwu (零一万物)", BaseURL: "https://api.lingyiwanwu.com/v1", EnvKey: "LINGYIWANWU_API_KEY", Behavior: BehaviorFull},
	"llama":                               {ID: "llama", DisplayName: "Llama", BaseURL: "https://api.llama.com/compat/v1/", EnvKey: "LLAMA_API_KEY", Behavior: BehaviorFull},
	"llamagate":                           {ID: "llamagate", DisplayName: "Llamagate", BaseURL: "https://api.llamagate.dev/v1", EnvKey: "LLAMAGATE_API_KEY", Behavior: BehaviorFull},
	"llmgateway":                          {ID: "llmgateway", DisplayName: "LLM Gateway", BaseURL: "https://api.llmgateway.io/v1", EnvKey: "LLM_GATEWAY_API_KEY", Behavior: BehaviorFull},
	"llmtr":                               {ID: "llmtr", DisplayName: "LLMTR", BaseURL: "https://llmtr.com/v1", EnvKey: "LLMTR_API_KEY", Behavior: BehaviorFull},
	"longcat":                             {ID: "longcat", DisplayName: "LongCat", BaseURL: "https://api.longcat.chat/v1", EnvKey: "LONGCAT_API_KEY", Behavior: BehaviorFull},
	"lucidquery":                          {ID: "lucidquery", DisplayName: "LucidQuery", BaseURL: "https://api.lucidquery.com/v1", EnvKey: "LUCIDQUERY_API_KEY", Behavior: BehaviorFull},
	"lynkr":                               {ID: "lynkr", DisplayName: "Lynkr", BaseURL: "http://localhost:8081/v1", EnvKey: "LYNKR_API_KEY", Behavior: BehaviorFull},
	"matterai":                            {ID: "matterai", DisplayName: "Matter AI", BaseURL: "https://api.matterai.com/v1", EnvKey: "MATTERAI_API_KEY", Behavior: BehaviorFull},
	"meganova":                            {ID: "meganova", DisplayName: "Meganova", BaseURL: "https://api.meganova.ai/v1", EnvKey: "MEGANOVA_API_KEY", Behavior: BehaviorFull},
	"merge_gateway":                       {ID: "merge_gateway", DisplayName: "Merge Gateway", BaseURL: "https://api-gateway.merge.dev/v1/openai", EnvKey: "MERGE_GATEWAY_API_KEY", Behavior: BehaviorFull},
	"meta":                                {ID: "meta", DisplayName: "Meta", BaseURL: "https://api.meta.ai/v1", EnvKey: "MODEL_API_KEY", Behavior: BehaviorFull},
	"meta_llama":                          {ID: "meta_llama", DisplayName: "Meta Llama API", BaseURL: "https://api.llama.com/compat/v1", EnvKey: "LLAMA_API_KEY", Behavior: BehaviorFull},
	"mimo":                                {ID: "mimo", DisplayName: "Mimo", BaseURL: "https://api.xiaomimimo.com/v1", EnvKey: "MIMO_API_KEY", Behavior: BehaviorFull},
	"minimax":                             {ID: "minimax", DisplayName: "MiniMax", BaseURL: "https://api.minimax.io/anthropic", EnvKey: "MINIMAX_API_KEY", Behavior: BehaviorFull, Protocol: ProtocolAnthropic},
	"minimax_cn":                          {ID: "minimax_cn", DisplayName: "MiniMax (minimaxi.com)", BaseURL: "https://api.minimaxi.com/anthropic", EnvKey: "MINIMAX_API_KEY", Behavior: BehaviorFull, Protocol: ProtocolAnthropic},
	"minimax_cn_coding_plan":              {ID: "minimax_cn_coding_plan", DisplayName: "MiniMax Token Plan (minimaxi.com)", BaseURL: "https://api.minimaxi.com/anthropic", EnvKey: "MINIMAX_API_KEY", Behavior: BehaviorFull, Protocol: ProtocolAnthropic},
	"minimax_coding_plan":                 {ID: "minimax_coding_plan", DisplayName: "MiniMax Token Plan (minimax.io)", BaseURL: "https://api.minimax.io/anthropic", EnvKey: "MINIMAX_API_KEY", Behavior: BehaviorFull, Protocol: ProtocolAnthropic},
	"mira":                                {ID: "mira", DisplayName: "Mira", BaseURL: "https://api.mira.so/v1", EnvKey: "MIRA_API_KEY", Behavior: BehaviorFull},
	"mixlayer":                            {ID: "mixlayer", DisplayName: "Mixlayer", BaseURL: "https://models.mixlayer.ai/v1", EnvKey: "MIXLAYER_API_KEY", Behavior: BehaviorFull},
	"moark":                               {ID: "moark", DisplayName: "Moark", BaseURL: "https://api.moark.com/v1", EnvKey: "MOARK_API_KEY", Behavior: BehaviorFull},
	"modal":                               {ID: "modal", DisplayName: "Modal", BaseURL: "https://modal.com/v1", EnvKey: "MODAL_API_KEY", Behavior: BehaviorFull},
	"model_oracle_ai":                     {ID: "model_oracle_ai", DisplayName: "Model Oracle AI", BaseURL: "https://api.modeloracle.com/api/v1", EnvKey: "MODEL_ORACLE_API_KEY", Behavior: BehaviorFull},
	"modelscope":                          {ID: "modelscope", DisplayName: "ModelScope", BaseURL: "https://api-inference.modelscope.cn/v1", EnvKey: "MODELSCOPE_API_KEY", Behavior: BehaviorFull},
	"moonshotai":                          {ID: "moonshotai", DisplayName: "Moonshot AI", BaseURL: "https://api.moonshot.cn/v1", EnvKey: "MOONSHOT_API_KEY", Behavior: BehaviorFull},
	"moonshotai_cn":                       {ID: "moonshotai_cn", DisplayName: "Moonshot AI (China)", BaseURL: "https://api.moonshot.cn/v1", EnvKey: "MOONSHOT_API_KEY", Behavior: BehaviorFull},
	"morph":                               {ID: "morph", DisplayName: "Morph LLM", BaseURL: "https://api.morphllm.com/v1", EnvKey: "MORPH_API_KEY", Behavior: BehaviorFull},
	"nanogpt":                             {ID: "nanogpt", DisplayName: "NanoGPT", BaseURL: "https://api.nanogpt.com/v1", EnvKey: "NANOGPT_API_KEY", Behavior: BehaviorFull},
	"ncompass":                            {ID: "ncompass", DisplayName: "Ncompass", BaseURL: "https://api.ncompass.tech/v1", EnvKey: "NCOMPASS_API_KEY", Behavior: BehaviorFull},
	"nearai":                              {ID: "nearai", DisplayName: "NEAR AI Cloud", BaseURL: "https://cloud-api.near.ai/v1", EnvKey: "NEARAI_API_KEY", Behavior: BehaviorFull},
	"nebius":                              {ID: "nebius", DisplayName: "Nebius AI", BaseURL: "https://api.studio.nebius.ai/v1", EnvKey: "NEBIUS_API_KEY", Behavior: BehaviorFull},
	"neon":                                {ID: "neon", DisplayName: "Neon", EnvKey: "NEON_AI_GATEWAY_TOKEN", Behavior: BehaviorFull},
	"neuralwatt":                          {ID: "neuralwatt", DisplayName: "Neuralwatt", BaseURL: "https://api.neuralwatt.com/v1", EnvKey: "NEURALWATT_API_KEY", Behavior: BehaviorFull},
	"nextbit":                             {ID: "nextbit", DisplayName: "NextBit", BaseURL: "https://api.nextbit.ai/v1", EnvKey: "NEXTBIT_API_KEY", Behavior: BehaviorFull},
	"nlp_cloud":                           {ID: "nlp_cloud", DisplayName: "NLP Cloud", BaseURL: "https://api.nlpcloud.io/v1", EnvKey: "NLPCLOUD_API_KEY", Behavior: BehaviorFull},
	"nous_research":                       {ID: "nous_research", DisplayName: "Nous Research", BaseURL: "https://api.nousresearch.com/v1", EnvKey: "NOUS_API_KEY", Behavior: BehaviorFull},
	"novita":                              {ID: "novita", DisplayName: "Novita AI", BaseURL: "https://api.novita.ai/v1", EnvKey: "NOVITA_API_KEY", Behavior: BehaviorFull},
	"nscale":                              {ID: "nscale", DisplayName: "Nscale", BaseURL: "https://inference.api.nscale.com/v1", EnvKey: "NSCALE_API_KEY", Behavior: BehaviorFull},
	"nvidia_nim":                          {ID: "nvidia_nim", DisplayName: "NVIDIA NIM", BaseURL: "https://integrate.api.nvidia.com/v1", EnvKey: "NVIDIA_API_KEY", Behavior: BehaviorFull},
	"oci":                                 {ID: "oci", DisplayName: "OCI", EnvKey: "OCI_API_KEY", Behavior: BehaviorFull},
	"ofox":                                {ID: "ofox", DisplayName: "OfoxAI", BaseURL: "https://api.ofox.ai/v1", EnvKey: "OFOX_API_KEY", Behavior: BehaviorFull},
	"ohmygpt":                             {ID: "ohmygpt", DisplayName: "OhMyGPT", BaseURL: "https://api.ohmygpt.com/v1", EnvKey: "OHMYGPT_API_KEY", Behavior: BehaviorFull},
	"ollama_cloud":                        {ID: "ollama_cloud", DisplayName: "Ollama Cloud", BaseURL: "https://api.ollama.com/v1", EnvKey: "OLLAMA_CLOUD_API_KEY", Behavior: BehaviorFull, Protocol: ProtocolResponses},
	"openaimax":                           {ID: "openaimax", DisplayName: "OpenAIMax", BaseURL: "https://api.openaimax.com/v1", EnvKey: "OPENAIMAX_API_KEY", Behavior: BehaviorFull},
	"openaisb":                            {ID: "openaisb", DisplayName: "OpenAI-SB", BaseURL: "https://api.openaisb.com/v1", EnvKey: "OPENAISB_API_KEY", Behavior: BehaviorFull},
	"opencode":                            {ID: "opencode", DisplayName: "OpenCode Zen", EnvKey: "OPENCODE_API_KEY", Behavior: BehaviorFull},
	"opencode_go":                         {ID: "opencode_go", DisplayName: "OpenCode Go", BaseURL: "https://api.opencode.dev/v1", EnvKey: "OPENCODE_GO_API_KEY", Behavior: BehaviorFull},
	"opencode_zen":                        {ID: "opencode_zen", DisplayName: "OpenCode Zen", BaseURL: "https://api.opencode.zen/v1", EnvKey: "OPENCODE_ZEN_API_KEY", Behavior: BehaviorFull},
	"orcarouter":                          {ID: "orcarouter", DisplayName: "OrcaRouter", BaseURL: "https://api.orcarouter.com/v1", EnvKey: "ORCAROUTER_API_KEY", Behavior: BehaviorFull},
	"ovhcloud":                            {ID: "ovhcloud", DisplayName: "OVHcloud AI", BaseURL: "https://oai.endpoints.kepler.ai.cloud.ovh.net/v1", EnvKey: "OVHCLOUD_API_KEY", Behavior: BehaviorFull},
	"parasail":                            {ID: "parasail", DisplayName: "Parasail", BaseURL: "https://api.parasail.io/v1", EnvKey: "PARASAIL_API_KEY", Behavior: BehaviorFull},
	"perfxcloud":                          {ID: "perfxcloud", DisplayName: "PerfXCloud", BaseURL: "https://api.perfxcloud.com/v1", EnvKey: "PERFXCLOUD_API_KEY", Behavior: BehaviorFull},
	"perplexity":                          {ID: "perplexity", DisplayName: "Perplexity", BaseURL: "https://api.perplexity.ai", EnvKey: "PERPLEXITY_API_KEY", Behavior: BehaviorFull},
	"perplexity_agent":                    {ID: "perplexity_agent", DisplayName: "Perplexity Agent", BaseURL: "https://api.perplexity.ai/v1", EnvKey: "PERPLEXITY_API_KEY", Behavior: BehaviorFull},
	"petals":                              {ID: "petals", DisplayName: "Petals", BaseURL: "https://api.petals.dev/v1", EnvKey: "PETALS_API_KEY", Behavior: BehaviorFull},
	"pinstripes":                          {ID: "pinstripes", DisplayName: "Pinstripes", BaseURL: "https://api.pinstripes.io/v1", EnvKey: "PINSTRIPES_API_KEY", Behavior: BehaviorFull},
	"pioneer":                             {ID: "pioneer", DisplayName: "Pioneer", BaseURL: "https://api.pioneer.ai/v1", EnvKey: "PIONEER_API_KEY", Behavior: BehaviorFull},
	"poe":                                 {ID: "poe", DisplayName: "Poe", BaseURL: "https://api.poe.com/v1", EnvKey: "POE_API_KEY", Behavior: BehaviorFull},
	"poolside":                            {ID: "poolside", DisplayName: "Poolside", BaseURL: "https://inference.poolside.ai/v1", EnvKey: "POOLSIDE_API_KEY", Behavior: BehaviorFull},
	"portkey":                             {ID: "portkey", DisplayName: "Portkey Gateway", BaseURL: "https://api.portkey.ai/v1", EnvKey: "PORTKEY_API_KEY", Behavior: BehaviorFull},
	"ppinfra":                             {ID: "ppinfra", DisplayName: "PPInfra（PPIO 派欧云）", BaseURL: "https://api.ppio.com/openai", EnvKey: "PPIO_API_KEY", Behavior: BehaviorFull},
	"predibase":                           {ID: "predibase", DisplayName: "Predibase", BaseURL: "https://serving.app.predibase.com/v1", EnvKey: "PREDIBASE_API_KEY", Behavior: BehaviorFull},
	"privatemode_ai":                      {ID: "privatemode_ai", DisplayName: "Privatemode AI", BaseURL: "http://localhost:8080/v1", EnvKey: "PRIVATEMODE_API_KEY", Behavior: BehaviorFull},
	"publicai":                            {ID: "publicai", DisplayName: "Publicai", BaseURL: "https://platform.publicai.co/v1", EnvKey: "PUBLICAI_API_KEY", Behavior: BehaviorFull},
	"qihang_ai":                           {ID: "qihang_ai", DisplayName: "QiHang（启航 AI）", BaseURL: "https://api.qhaigc.net/v1", EnvKey: "QIHANG_API_KEY", Behavior: BehaviorFull},
	"qihoo360":                            {ID: "qihoo360", DisplayName: "360 AI", BaseURL: "https://api.360.cn/v1", EnvKey: "AI360_API_KEY", Behavior: BehaviorFull},
	"qiniu_ai":                            {ID: "qiniu_ai", DisplayName: "Qiniu AI", BaseURL: "https://api.qiniu.com/v1", EnvKey: "QINIU_API_KEY", Behavior: BehaviorFull},
	"regolo_ai":                           {ID: "regolo_ai", DisplayName: "Regolo AI", BaseURL: "https://api.regolo.ai/v1", EnvKey: "REGOLO_API_KEY", Behavior: BehaviorFull},
	"reka_ai":                             {ID: "reka_ai", DisplayName: "Reka AI", BaseURL: "https://api.reka.ai/v1", EnvKey: "REKA_API_KEY", Behavior: BehaviorFull},
	"requesty":                            {ID: "requesty", DisplayName: "Requesty", BaseURL: "https://api.requesty.ai/v1", EnvKey: "REQUESTY_API_KEY", Behavior: BehaviorFull},
	"reve":                                {ID: "reve", DisplayName: "Reve", BaseURL: "https://api.reve.ai/v1", EnvKey: "REVE_API_KEY", Behavior: BehaviorFull},
	"routing_run":                         {ID: "routing_run", DisplayName: "routing.run", BaseURL: "https://api.routing.run/v1", EnvKey: "ROUTING_RUN_API_KEY", Behavior: BehaviorFull},
	"sakana":                              {ID: "sakana", DisplayName: "Sakana AI", BaseURL: "https://api.sakana.ai/v1", EnvKey: "SAKANA_API_KEY", Behavior: BehaviorFull},
	"sambanova":                           {ID: "sambanova", DisplayName: "SambaNova", BaseURL: "https://api.sambanova.ai/v1", EnvKey: "SAMBANOVA_API_KEY", Behavior: BehaviorFull},
	"sarvam":                              {ID: "sarvam", DisplayName: "Sarvam AI", BaseURL: "https://api.sarvam.ai/v1", EnvKey: "SARVAM_API_KEY", Behavior: BehaviorFull},
	"scaleway":                            {ID: "scaleway", DisplayName: "Scaleway AI", BaseURL: "https://api.scaleway.ai/v1", EnvKey: "SCALEWAY_API_KEY", Behavior: BehaviorFull},
	"scx_ai":                              {ID: "scx_ai", DisplayName: "SCX AI", BaseURL: "https://api.scx.ai/v1", EnvKey: "SCX_AI_API_KEY", Behavior: BehaviorFull},
	"siliconflow":                         {ID: "siliconflow", DisplayName: "SiliconFlow", BaseURL: "https://api.siliconflow.cn/v1", EnvKey: "SILICONFLOW_API_KEY", Behavior: BehaviorFull},
	"snowflake":                           {ID: "snowflake", DisplayName: "Snowflake", EnvKey: "SNOWFLAKE_PAT", Behavior: BehaviorFull},
	"snowflake_cortex":                    {ID: "snowflake_cortex", DisplayName: "Snowflake Cortex", EnvKey: "SNOWFLAKE_CORTEX_PAT", Behavior: BehaviorFull},
	"stackit":                             {ID: "stackit", DisplayName: "STACKIT", BaseURL: "https://api.openai-compat.model-serving.eu01.onstackit.cloud/v1", EnvKey: "STACKIT_API_KEY", Behavior: BehaviorFull},
	"stepfun":                             {ID: "stepfun", DisplayName: "StepFun (阶跃星辰)", BaseURL: "https://api.stepfun.com/v1", EnvKey: "STEPFUN_API_KEY", Behavior: BehaviorFull},
	"stepfun_ai_step_plan":                {ID: "stepfun_ai_step_plan", DisplayName: "StepFun Step Plan (Global)", BaseURL: "https://api.stepfun.ai/step_plan/v1", EnvKey: "STEPFUN_API_KEY", Behavior: BehaviorFull},
	"stepfun_step_plan":                   {ID: "stepfun_step_plan", DisplayName: "StepFun Step Plan (China)", BaseURL: "https://api.stepfun.com/step_plan/v1", EnvKey: "STEPFUN_API_KEY", Behavior: BehaviorFull},
	"subconscious":                        {ID: "subconscious", DisplayName: "Subconscious", BaseURL: "https://api.subconscious.dev/v1", EnvKey: "SUBCONSCIOUS_API_KEY", Behavior: BehaviorFull},
	"submodel":                            {ID: "submodel", DisplayName: "SubModel", BaseURL: "https://api.submodel.com/v1", EnvKey: "SUBMODEL_API_KEY", Behavior: BehaviorFull},
	"synthetic":                           {ID: "synthetic", DisplayName: "Synthetic", BaseURL: "https://api.synthetic.new/openai/v1", EnvKey: "SYNTHETIC_API_KEY", Behavior: BehaviorFull},
	"tencent":                             {ID: "tencent", DisplayName: "Tencent (混元/Hunyuan)", BaseURL: "https://api.hunyuan.cloud.tencent.com/v1", EnvKey: "TENCENT_API_KEY", Behavior: BehaviorFull},
	"tencent_coding_plan":                 {ID: "tencent_coding_plan", DisplayName: "Tencent Coding Plan (China)", BaseURL: "https://api.lkeap.cloud.tencent.com/coding/v3", EnvKey: "TENCENT_CODING_PLAN_API_KEY", Behavior: BehaviorFull},
	"tencent_token_plan":                  {ID: "tencent_token_plan", DisplayName: "Tencent Token Plan", BaseURL: "https://api.lkeap.cloud.tencent.com/plan/anthropic", EnvKey: "TENCENT_TOKEN_PLAN_API_KEY", Behavior: BehaviorFull, Protocol: ProtocolAnthropic},
	"tencent_token_plan_enterprise_auto":  {ID: "tencent_token_plan_enterprise_auto", DisplayName: "腾讯云 Token Plan / Token Plan 企业版轻享套餐", BaseURL: "https://tokenhub.tencentmaas.com/plan/anthropic", EnvKey: "TENCENT_TOKEN_PLAN_ENTERPRISE_API_KEY", Behavior: BehaviorFull, Protocol: ProtocolAnthropic},
	"tencent_token_plan_enterprise_pro":   {ID: "tencent_token_plan_enterprise_pro", DisplayName: "腾讯云 Token Plan / Token Plan 企业版专业套餐", BaseURL: "https://tokenhub.tencentmaas.com/plan/anthropic", EnvKey: "TENCENT_TOKEN_PLAN_ENTERPRISE_API_KEY", Behavior: BehaviorFull, Protocol: ProtocolAnthropic},
	"tencent_token_plan_general_personal": {ID: "tencent_token_plan_general_personal", DisplayName: "腾讯云 Token Plan / 通用 Token Plan（个人版）", BaseURL: "https://api.lkeap.cloud.tencent.com/plan/anthropic", EnvKey: "TENCENT_TOKEN_PLAN_API_KEY", Behavior: BehaviorFull, Protocol: ProtocolAnthropic},
	"tencent_token_plan_hy_personal":      {ID: "tencent_token_plan_hy_personal", DisplayName: "腾讯云 Token Plan / Hy Token Plan（个人版）", BaseURL: "https://api.lkeap.cloud.tencent.com/plan/anthropic", EnvKey: "TENCENT_TOKEN_PLAN_API_KEY", Behavior: BehaviorFull, Protocol: ProtocolAnthropic},
	"tencent_tokenhub":                    {ID: "tencent_tokenhub", DisplayName: "Tencent TokenHub", BaseURL: "https://tokenhub.tencentmaas.com/v1", EnvKey: "TENCENT_TOKENHUB_API_KEY", Behavior: BehaviorFull},
	"tensormesh":                          {ID: "tensormesh", DisplayName: "Tensormesh", BaseURL: "https://serverless.tensormesh.ai", EnvKey: "YOUR_API_KEY", Behavior: BehaviorFull},
	"the_grid_ai":                         {ID: "the_grid_ai", DisplayName: "The Grid AI", BaseURL: "https://thegrid.ai/docs", EnvKey: "THEGRIDAI_API_KEY", Behavior: BehaviorFull},
	"thinkingmachines":                    {ID: "thinkingmachines", DisplayName: "Thinking Machines", BaseURL: "https://tinker.thinkingmachines.dev/services/tinker-prod/oai/api/v1", EnvKey: "TINKER_API_KEY", Behavior: BehaviorFull},
	"tinfoil":                             {ID: "tinfoil", DisplayName: "Tinfoil", BaseURL: "https://inference.tinfoil.sh/v1", EnvKey: "TINFOIL_API_KEY", Behavior: BehaviorFull},
	"togetherai":                          {ID: "togetherai", DisplayName: "Together AI", BaseURL: "https://api.together.xyz/v1", EnvKey: "TOGETHER_API_KEY", Behavior: BehaviorFull},
	"tokenflux":                           {ID: "tokenflux", DisplayName: "Tokenflux", BaseURL: "https://tokenflux.ai/v1", EnvKey: "TOKENFLUX_API_KEY", Behavior: BehaviorFull},
	"tokenpony":                           {ID: "tokenpony", DisplayName: "TokenPony", BaseURL: "https://api.tokenpony.com/v1", EnvKey: "TOKENPONY_API_KEY", Behavior: BehaviorFull},
	"trustedrouter":                       {ID: "trustedrouter", DisplayName: "TrustedRouter", BaseURL: "https://api.trustedrouter.com/v1", EnvKey: "TRUSTEDROUTER_API_KEY", Behavior: BehaviorFull},
	"tundra":                              {ID: "tundra", DisplayName: "Tundra", BaseURL: "https://api.tundra.ai/v1", EnvKey: "TUNDRA_API_KEY", Behavior: BehaviorFull},
	"umans_ai":                            {ID: "umans_ai", DisplayName: "Umans AI", BaseURL: "https://api.code.umans.ai/v1", EnvKey: "UMANS_AI_API_KEY", Behavior: BehaviorFull},
	"unorouter":                           {ID: "unorouter", DisplayName: "UnoRouter", BaseURL: "https://unorouter.com/en", EnvKey: "UNOROUTER_API_KEY", Behavior: BehaviorFull},
	"upstage":                             {ID: "upstage", DisplayName: "Upstage", BaseURL: "https://api.upstage.ai/v1", EnvKey: "UPSTAGE_API_KEY", Behavior: BehaviorFull},
	"v0":                                  {ID: "v0", DisplayName: "v0 (Vercel)", BaseURL: "https://api.v0.dev/v1", EnvKey: "V0_API_KEY", Behavior: BehaviorFull},
	"venice":                              {ID: "venice", DisplayName: "Venice", BaseURL: "https://api.venice.ai/api/v1", EnvKey: "VENICE_API_KEY", Behavior: BehaviorFull},
	"vercel":                              {ID: "vercel", DisplayName: "Vercel AI Gateway", BaseURL: "https://ai-gateway.vercel.sh/v1", EnvKey: "AI_GATEWAY_API_KEY", Behavior: BehaviorFull, Protocol: ProtocolResponses},
	"vivgrid":                             {ID: "vivgrid", DisplayName: "Vivgrid", BaseURL: "https://api.vivgrid.com/v1", EnvKey: "VIVGRID_API_KEY", Behavior: BehaviorFull},
	"volc_engine":                         {ID: "volc_engine", DisplayName: "VolcEngine", BaseURL: "https://ark.cn-beijing.volces.com", EnvKey: "ARK_API_KEY", Behavior: BehaviorFull},
	"vultr":                               {ID: "vultr", DisplayName: "Vultr", BaseURL: "https://api.vultrinference.com/v1", EnvKey: "VULTR_API_KEY", Behavior: BehaviorFull},
	"wafer":                               {ID: "wafer", DisplayName: "Wafer", BaseURL: "https://api.wafer.ai/v1", EnvKey: "WAFER_API_KEY", Behavior: BehaviorFull},
	"wandb":                               {ID: "wandb", DisplayName: "Weights & Biases", BaseURL: "https://api.inference.wandb.ai/v1", EnvKey: "WANDB_API_KEY", Behavior: BehaviorFull},
	"xiaomi_token_plan_ams":               {ID: "xiaomi_token_plan_ams", DisplayName: "Xiaomi Token Plan (Europe)", BaseURL: "https://token-plan-ams.xiaomimimo.com/v1", EnvKey: "MIMO_API_KEY", Behavior: BehaviorFull},
	"xiaomi_token_plan_cn":                {ID: "xiaomi_token_plan_cn", DisplayName: "Xiaomi Token Plan (China)", BaseURL: "https://token-plan-cn.xiaomimimo.com/v1", EnvKey: "MIMO_API_KEY", Behavior: BehaviorFull},
	"xiaomi_token_plan_sgp":               {ID: "xiaomi_token_plan_sgp", DisplayName: "Xiaomi Token Plan (Singapore)", BaseURL: "https://token-plan-sgp.xiaomimimo.com/v1", EnvKey: "MIMO_API_KEY", Behavior: BehaviorFull},
	"xiaomimimo":                          {ID: "xiaomimimo", DisplayName: "Xiaomi MiMo", BaseURL: "https://mimo.xiaomi.com/v1", EnvKey: "XIAOMI_API_KEY", Behavior: BehaviorFull},
	"xpersona":                            {ID: "xpersona", DisplayName: "Xpersona", EnvKey: "XPERSONA_API_KEY", Behavior: BehaviorFull},
	"xunfei":                              {ID: "xunfei", DisplayName: "Xunfei", BaseURL: "https://spark-api-open.xf-yun.com/v1", EnvKey: "XUNFEI_API_PASSWORD", Behavior: BehaviorFull},
	"zai":                                 {ID: "zai", DisplayName: "Zai", BaseURL: "https://api.z.ai/api/paas/v4", EnvKey: "ZAI_API_KEY", Behavior: BehaviorFull},
	"zai_coding_plan":                     {ID: "zai_coding_plan", DisplayName: "Z.AI Coding Plan", BaseURL: "https://api.z.ai/api/anthropic", EnvKey: "ZHIPU_API_KEY", Behavior: BehaviorFull, Protocol: ProtocolAnthropic, APIKeyHeader: "Authorization", APIKeyPrefix: "Bearer "},
	"zeldoc":                              {ID: "zeldoc", DisplayName: "Zeldoc", BaseURL: "https://api.zeldoc.ai/v1", EnvKey: "ZELDOC_API_KEY", Behavior: BehaviorFull},
	"zenmux":                              {ID: "zenmux", DisplayName: "ZenMux", BaseURL: "https://zenmux.ai/api/v1", EnvKey: "ZENMUX_API_KEY", Behavior: BehaviorFull},
	"zhipu_v4":                            {ID: "zhipu_v4", DisplayName: "ZhipuV4", BaseURL: "https://open.bigmodel.cn/api/paas/v4", EnvKey: "ZHIPU_API_KEY", Behavior: BehaviorFull},
	"zhipuai_coding_plan":                 {ID: "zhipuai_coding_plan", DisplayName: "Zhipu AI Coding Plan", BaseURL: "https://api.z.ai/api/anthropic", EnvKey: "ZHIPU_API_KEY", Behavior: BehaviorFull, Protocol: ProtocolAnthropic, APIKeyHeader: "Authorization", APIKeyPrefix: "Bearer "},
	"huggingface":                         {ID: "huggingface", DisplayName: "Hugging Face Inference Providers", BaseURL: "https://router.huggingface.co/v1", EnvKey: "HF_TOKEN", Behavior: BehaviorFull, Protocol: ProtocolResponses},
	"litellm_proxy":                       {ID: "litellm_proxy", DisplayName: "LiteLLM Proxy", BaseURL: "http://localhost:4000/v1", EnvKey: "LITELLM_API_KEY", Behavior: BehaviorFull, Protocol: ProtocolResponses, AllowEmptyAPIKey: true},
	"lmstudio":                            {ID: "lmstudio", DisplayName: "LM Studio", BaseURL: "http://localhost:1234/v1", EnvKey: "LMSTUDIO_API_KEY", Behavior: BehaviorFull, Protocol: ProtocolResponses, AllowEmptyAPIKey: true},
	"ollama":                              {ID: "ollama", DisplayName: "Ollama", BaseURL: "http://localhost:11434/v1", EnvKey: "OLLAMA_API_KEY", Behavior: BehaviorFull, Protocol: ProtocolResponses, AllowEmptyAPIKey: true},
	"openrouter":                          {ID: "openrouter", DisplayName: "OpenRouter", BaseURL: "https://openrouter.ai/api/v1", EnvKey: "OPENROUTER_API_KEY", Behavior: BehaviorFull, Protocol: ProtocolResponses},
	"sglang":                              {ID: "sglang", DisplayName: "SGLang", BaseURL: "http://localhost:30000/v1", EnvKey: "SGLANG_API_KEY", Behavior: BehaviorFull, Protocol: ProtocolResponses, AllowEmptyAPIKey: true},
	"vllm":                                {ID: "vllm", DisplayName: "vLLM", BaseURL: "http://localhost:8000/v1", EnvKey: "VLLM_API_KEY", Behavior: BehaviorFull, Protocol: ProtocolResponses, AllowEmptyAPIKey: true},
}
